services:
  redis:
    image: redis:6.2.14-alpine3.20
    restart: always
    volumes:
      - ./.cnpmcore/redis:/data
    networks:
      - cnpm

  mysql:
    image: mysql:8.4.1
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe123!@#
      MYSQL_DATABASE: cnpmcore
    volumes:
      - ./.cnpmcore/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - cnpm

  npm:
    image: cnpmcore:3.61.6
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      CNPMCORE_MYSQL_HOST: mysql
      CNPMCORE_MYSQL_PASSWORD: qwe123!@#
      CNPMCORE_MYSQL_DATABASE: cnpmcore
      CNPMCORE_REDIS_HOST: redis
      CNPMCORE_PASSWORD: admin@cnpmjs.org
      CNPMCORE_DATA_DIR: /root/storage
      CNPMCORE_CONFIG_REGISTRY: http://127.0.0.1:7001
    volumes:
      - ./.cnpmcore/storage:/root/storage
      - ./.cnpmcore/logs:/root/logs
    ports:
      - 7001:7001
    networks:
      - cnpm

networks:
  cnpm:
    name: cnpm
    driver: bridge
